name: Full CI functions/unit tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [ 'master', 'develop' ]
    pull_request:
        branches: [ 'master', 'develop' ]


jobs:
    build:
        runs-on: ${{ matrix.operating-system }}
        env:
            SYMFONY_DEPRECATIONS_HELPER: disabled

        name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}

        strategy:
            fail-fast: true
            matrix:
                operating-system: [ ubuntu-latest ]
                php: [ '8.0', '8.1' ]
                symfony: [ '5.4.*', '6.0.*' ]

        steps:
            -   uses: actions/checkout@master

            -   name: Setup PHP ${{ matrix.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: flex

            -   name: Download dependencies
                env:
                    SYMFONY_REQUIRE: ${{ matrix.symfony }}
                uses: ramsey/composer-install@v1

            -   name: Run code sniffer
                run: ./vendor/bin/phpcs

            -   name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
                run: ./vendor/bin/phpunit
